(function(){
'use strict';
const $=id=>document.getElementById(id);
const cfg=window.SPENCER_LIVE_CONFIG||{};
const configured=Boolean(window.supabase&&cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY);
const db=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}):null;
const panels=['choice','hostSetup','joinSetup','lobby','race','results'];
const COLORS=['#ef4444','#38bdf8','#facc15','#a78bfa'];
const HELMETS=['🔴','🔵','🟡','🟣'];
const TRACK_N=520,TRACK_HALF=91;
let trackPts=[],room=null,riders=[],role=null,myId=null,channel=null;
let bike=null,lapTimes=[],offTrackEvents=0,leftHeld=false,rightHeld=false,running=false,raf=0,lastTs=0,startTs=0,lapStartTs=0,lastPush=0,lastRaceNumber=0,finishing=false;
const canvas=$('track'),ctx=canvas.getContext('2d');

function show(id){panels.forEach(x=>$(x).classList.toggle('hidden',x!==id));}
function cleanCode(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4);}
function cleanName(v){return String(v||'').trim().replace(/\s+/g,' ').slice(0,24);}
function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<4;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s;}
function formatMs(ms){if(!Number.isFinite(Number(ms)))return '—';return (Number(ms)/1000).toFixed(2)+'s';}
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function msg(target,text,bad=true){target.innerHTML=text?'<div class="status '+(bad?'warn':'good')+'">'+escapeHtml(text)+'</div>':'';}
function setService(text,good=true){$('serviceStatus').textContent=text;$('serviceStatus').className='status '+(good?'good':'warn');}
function version(){return window.SPENCER_GAMES_VERSION||'v4.9';}

function makeTrack(){trackPts=[];const cx=450,cy=323,halfStraight=195,r=135,straightLen=halfStraight*2,arcLen=Math.PI*r,total=straightLen*2+arcLen*2;for(let i=0;i<TRACK_N;i++){const d=i/TRACK_N*total;let x,y,a;if(d<straightLen){x=cx-halfStraight+d;y=cy+r;a=0}else if(d<straightLen+arcLen){const q=(d-straightLen)/r,ang=Math.PI/2-q;x=cx+halfStraight+r*Math.cos(ang);y=cy+r*Math.sin(ang);a=ang-Math.PI/2}else if(d<straightLen+arcLen+straightLen){const q2=d-straightLen-arcLen;x=cx+halfStraight-q2;y=cy-r;a=Math.PI}else{const q3=(d-straightLen-arcLen-straightLen)/r,ang2=-Math.PI/2-q3;x=cx-halfStraight+r*Math.cos(ang2);y=cy+r*Math.sin(ang2);a=ang2-Math.PI/2}trackPts.push({x,y,a});}}
function nearest(x,y){let best=1e9,idx=0;for(let i=0;i<trackPts.length;i++){const p=trackPts[i],dx=x-p.x,dy=y-p.y,d=dx*dx+dy*dy;if(d<best){best=d;idx=i}}return{idx,dist:Math.sqrt(best),p:trackPts[idx]};}
function angleDiff(a,b){return((b-a+Math.PI*3)%(Math.PI*2))-Math.PI;}
makeTrack();

function drawStadium(){ctx.clearRect(0,0,900,650);ctx.fillStyle='#123527';ctx.fillRect(0,0,900,650);ctx.fillStyle='#071521';ctx.fillRect(0,0,900,58);ctx.fillRect(0,592,900,58);ctx.fillStyle='#ff6b1a';ctx.fillRect(0,55,900,3);ctx.fillRect(0,592,900,3);for(let i=0;i<34;i++){ctx.fillStyle=i%3===0?'#d7e0e7':i%3===1?'#e85b20':'#476984';ctx.fillRect(12+i*27,17+(i%2)*13,9,9);ctx.fillRect(12+i*27,612-(i%2)*13,9,9)}const path=new Path2D();path.moveTo(trackPts[0].x,trackPts[0].y);for(let j=1;j<trackPts.length;j++)path.lineTo(trackPts[j].x,trackPts[j].y);path.closePath();ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='#dce4e9';ctx.lineWidth=224;ctx.stroke(path);ctx.strokeStyle='#4d2e20';ctx.lineWidth=216;ctx.stroke(path);ctx.strokeStyle='#9d6038';ctx.lineWidth=190;ctx.stroke(path);ctx.strokeStyle='rgba(53,28,18,.42)';ctx.lineWidth=5;ctx.setLineDash([19,25]);ctx.stroke(path);ctx.setLineDash([]);ctx.textAlign='center';ctx.fillStyle='rgba(255,255,255,.84)';ctx.font='1000 31px sans-serif';ctx.fillText('SPENCER',450,304);ctx.fillStyle='#ff6b1a';ctx.font='1000 22px sans-serif';ctx.fillText('SPEEDWAY LIVE',450,331);ctx.fillStyle='rgba(220,228,233,.58)';ctx.font='800 11px sans-serif';ctx.fillText('SIMULTANEOUS ONLINE HEAT',450,351);const s=trackPts[0],nx=-Math.sin(s.a),ny=Math.cos(s.a);ctx.strokeStyle='#fff';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(s.x+nx*TRACK_HALF,s.y+ny*TRACK_HALF);ctx.lineTo(s.x-nx*TRACK_HALF,s.y-ny*TRACK_HALF);ctx.stroke();}
function drawBikeState(state,rider,label){if(!state)return;const h=Number(state.heading)||0,bias=((Number(rider.color_index)||0)-1.5)*7,x=Number(state.x)-Math.sin(h)*bias,y=Number(state.y)+Math.cos(h)*bias;ctx.save();ctx.translate(x,y);ctx.rotate(h);const steer=Number(state.steer)||0,va=Number(state.vel_angle)||h,lean=Math.max(-.55,Math.min(.55,steer*.42+angleDiff(va,h)*.7));ctx.rotate(lean*.22);ctx.shadowBlur=13;ctx.shadowColor=COLORS[rider.color_index]||'#fff';ctx.fillStyle='#151515';ctx.fillRect(-21,-7,42,14);ctx.fillStyle=COLORS[rider.color_index]||'#fff';ctx.fillRect(-9,-11,21,22);ctx.fillStyle='#d9d9d9';ctx.fillRect(-24,-4,8,8);ctx.fillRect(17,-4,8,8);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(1,-1,5.5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(label){ctx.rotate(-h);ctx.font='900 17px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='rgba(5,18,30,.88)';ctx.beginPath();ctx.arc(0,-27,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(HELMETS[rider.color_index]||'🏍️',0,-27)}ctx.restore();}
function stateForRider(r){if(r.id===myId&&bike)return bike;return{x:r.x,y:r.y,heading:r.heading,vel_angle:r.vel_angle,speed:r.speed,steer:r.steer,progress_steps:r.progress_steps,lap:r.lap};}
function renderTrack(){drawStadium();const sorted=riders.slice().sort((a,b)=>Number(a.color_index)-Number(b.color_index));sorted.forEach(r=>drawBikeState(stateForRider(r),r,true));}

function renderRiders(){const box=$('riders');box.innerHTML='';if(!riders.length){box.innerHTML='<div class="note">Waiting for riders…</div>';return;}riders.slice().sort((a,b)=>a.color_index-b.color_index).forEach(r=>{const d=document.createElement('div');d.className='rider';d.innerHTML='<span class="dot" style="background:'+COLORS[r.color_index]+'"></span><div><b>'+escapeHtml(r.name)+(r.id===myId?' · YOU':'')+'</b><small>'+(r.finished?'Finished '+formatMs(r.finish_ms):'Ready in gate '+(r.color_index+1))+'</small></div>';box.appendChild(d);});}
function standingsOrder(){return riders.slice().sort((a,b)=>{if(a.finished&&b.finished)return Number(a.finish_ms)-Number(b.finish_ms);if(a.finished!==b.finished)return a.finished?-1:1;return Number(b.progress_steps)-Number(a.progress_steps);});}
function renderStandings(targetId){const box=$(targetId);box.innerHTML='';const order=standingsOrder();order.forEach((r,i)=>{const d=document.createElement('div');d.className='standing';const status=r.finished?formatMs(r.finish_ms):('Lap '+Math.min((Number(r.lap)||0)+1,room?room.lap_count:3));d.innerHTML='<div class="place">'+(i+1)+'.</div><div><b><span style="color:'+COLORS[r.color_index]+'">'+(HELMETS[r.color_index]||'🏍️')+'</span> '+escapeHtml(r.name)+'</b><div class="note">Best '+formatMs(r.best_lap_ms)+'</div></div><div class="time">'+status+'</div>';box.appendChild(d);});if(role==='rider'&&myId){const pos=order.findIndex(r=>r.id===myId);$('positionHud').textContent=pos>=0?(pos+1)+' / '+order.length:'—';}}
function renderLobby(){if(!room)return;$('roomCode').textContent=room.code;const url=new URL(location.href);url.search='';url.searchParams.set('join',room.code);$('joinLink').textContent=url.toString();renderRiders();$('hostLobbyTools').classList.toggle('hidden',role!=='host');$('startRace').disabled=role!=='host'||riders.length<2||riders.length>4||room.status!=='lobby';$('lobbyStatus').textContent=room.status==='lobby'?(riders.length<2?'Waiting for at least 2 riders…':riders.length+' riders ready · '+room.lap_count+' laps'):room.status.toUpperCase();show('lobby');}
function renderRace(){renderTrack();renderStandings('liveStandings');$('controls').classList.toggle('hidden',role!=='rider'||!running);$('hostRaceTools').classList.toggle('hidden',role!=='host');$('raceAgain').classList.toggle('hidden',!room||room.status!=='finished');if(role==='host')$('lapHud').textContent=room?room.lap_count+' laps':'—';show('race');}
function renderResults(){renderStandings('finalStandings');$('resultHostTools').classList.toggle('hidden',role!=='host');show('results');loadAllTimeBoard();}

async function loadAllTimeBoard(){const box=$('allTimeBoard');if(!box||!db){if(box)box.innerHTML='<div class="note">Online records unavailable.</div>';return;}const {data,error}=await db.from('speedway_fastest_laps').select('player_name,best_lap_ms,created_at').order('best_lap_ms',{ascending:true}).limit(100);if(error){box.innerHTML='<div class="note">Run supabase/phase4-speedway.sql to enable online records.</div>';return;}const seen=new Set(),rows=[];(data||[]).forEach(r=>{const k=String(r.player_name).trim().toLowerCase();if(k&&!seen.has(k)){seen.add(k);rows.push(r);}});box.innerHTML='';rows.slice(0,10).forEach((r,i)=>{const d=document.createElement('div');d.className='boardRow';d.innerHTML='<span class="rank">'+(i+1)+'.</span><span class="name">'+escapeHtml(r.player_name)+'</span><span class="score">'+formatMs(r.best_lap_ms)+'</span>';box.appendChild(d);});if(!rows.length)box.innerHTML='<div class="note">No completed laps yet.</div>';}

async function loadRoom(){if(!room||!db)return false;const {data,error}=await db.from('speedway_rooms').select('*').eq('id',room.id).maybeSingle();if(error||!data)return false;room=data;return true;}
async function loadRiders(){if(!room||!db)return;const {data,error}=await db.from('speedway_riders').select('*').eq('room_id',room.id).order('joined_at');if(!error)riders=data||[];}
async function subscribe(){if(channel)await db.removeChannel(channel);channel=db.channel('speedway-'+room.id)
.on('postgres_changes',{event:'*',schema:'public',table:'speedway_rooms',filter:'id=eq.'+room.id},async payload=>{if(payload.eventType==='DELETE')return leaveLocal();room=payload.new;await handleRoomState();})
.on('postgres_changes',{event:'*',schema:'public',table:'speedway_riders',filter:'room_id=eq.'+room.id},async()=>{await loadRiders();renderRiders();if(room&&['countdown','racing'].includes(room.status)){renderRace();if(role==='host')checkFinished();}else if(room&&room.status==='finished')renderResults();})
.subscribe(status=>setService(status==='SUBSCRIBED'?'Online · Realtime connected':'Connecting…',status==='SUBSCRIBED'));}

async function handleRoomState(){if(!room)return;if(room.status==='closed'){leaveLocal();return;}if(room.status==='lobby'){running=false;finishing=false;resetLocalBike();await loadRiders();renderLobby();return;}if(room.status==='countdown'||room.status==='racing'){await loadRiders();armRace();return;}if(room.status==='finished'){running=false;cancelAnimationFrame(raf);await loadRiders();renderResults();}}

async function createRoom(){msg($('hostMessage'),'');if(!db){msg($('hostMessage'),'Supabase is not configured.');return;}const host=cleanName($('hostName').value)||'Host',laps=Number($('hostLaps').value)||3;$('createRoom').disabled=true;try{for(let i=0;i<8;i++){const code=randomCode();const {data,error}=await db.from('speedway_rooms').insert({code,host_name:host,lap_count:laps,status:'lobby'}).select('*').single();if(!error){room=data;role='host';myId=null;await loadRiders();await subscribe();renderLobby();return;}if(error.code!=='23505')throw error;}throw new Error('Could not create a unique room code.');}catch(e){msg($('hostMessage'),String(e.message||e).includes('speedway_rooms')?'Run supabase/phase4-speedway.sql first.':String(e.message||e));}finally{$('createRoom').disabled=false;}}
async function joinRoom(){msg($('joinMessage'),'');if(!db){msg($('joinMessage'),'Supabase is not configured.');return;}const code=cleanCode($('joinCode').value),name=cleanName($('riderName').value);if(code.length!==4){msg($('joinMessage'),'Enter the four-character room code.');return;}if(!name){msg($('joinMessage'),'Enter your rider name.');return;}$('joinRoom').disabled=true;try{const {data:r,error}=await db.from('speedway_rooms').select('*').eq('code',code).eq('status','lobby').maybeSingle();if(error)throw error;if(!r)throw new Error('Room not found or no longer open.');room=r;const {data:existing}=await db.from('speedway_riders').select('color_index').eq('room_id',room.id);const used=new Set((existing||[]).map(x=>Number(x.color_index)));let colour=0;while(used.has(colour)&&colour<4)colour++;const s=trackPts[0];const {data:joined,error:joinError}=await db.from('speedway_riders').insert({room_id:room.id,name,color_index:Math.min(colour,3),x:s.x,y:s.y}).select('*').single();if(joinError)throw joinError;role='rider';myId=joined.id;await loadRiders();await subscribe();renderLobby();}catch(e){const t=String(e.message||e);msg($('joinMessage'),/SPEEDWAY_ROOM_FULL/i.test(t)?'That heat already has four riders.':/SPEEDWAY_ROOM_NOT_OPEN/i.test(t)?'The tapes have already gone up for that room.':/speedway_rooms|speedway_riders/i.test(t)?'Run supabase/phase4-speedway.sql first.':t);}finally{$('joinRoom').disabled=false;}}

function resetLocalBike(){if(role!=='rider')return;const s=trackPts[0];bike={x:s.x,y:s.y,heading:0,vel_angle:0,speed:0,steer:0,nearestIdx:0,progress_steps:0,lap:0,lastIdx:0,off:false,farOffTime:0,finished:false};lapTimes=[];offTrackEvents=0;leftHeld=rightHeld=false;$('bestHud').textContent='—';$('timeHud').textContent='0.00';$('positionHud').textContent='—';$('lapHud').textContent=room?'1 / '+room.lap_count:'—';}
async function resetRoomForHeat(){if(role!=='host'||!room)return;const s=trackPts[0];await db.from('speedway_riders').update({x:s.x,y:s.y,heading:0,vel_angle:0,speed:0,steer:0,progress_steps:0,lap:0,finished:false,finish_ms:null,best_lap_ms:null,updated_at:new Date().toISOString()}).eq('room_id',room.id);const {data,error}=await db.from('speedway_rooms').update({status:'lobby',start_at:null,race_number:Number(room.race_number||1)+1,updated_at:new Date().toISOString()}).eq('id',room.id).select('*').single();if(!error){room=data;await loadRiders();renderLobby();}}
async function startRace(){if(role!=='host'||!room||riders.length<2)return;const s=trackPts[0];await db.from('speedway_riders').update({x:s.x,y:s.y,heading:0,vel_angle:0,speed:0,steer:0,progress_steps:0,lap:0,finished:false,finish_ms:null,best_lap_ms:null,updated_at:new Date().toISOString()}).eq('room_id',room.id);const startAt=new Date(Date.now()+4200).toISOString();const {data,error}=await db.from('speedway_rooms').update({status:'countdown',start_at:startAt,updated_at:new Date().toISOString()}).eq('id',room.id).select('*').single();if(!error){room=data;await loadRiders();armRace();}}
function armRace(){if(!room)return;const raceNo=Number(room.race_number||1),startAt=Date.parse(room.start_at||new Date().toISOString());if(role==='rider'&&lastRaceNumber!==raceNo)resetLocalBike();lastRaceNumber=raceNo;renderRace();const tick=()=>{if(!room||Number(room.race_number||1)!==raceNo)return;const left=startAt-Date.now();if(left>0){$('callout').textContent=left>3000?'3':left>2000?'2':left>1000?'1':'GO!';$('raceMsg').textContent='Tapes ready…';setTimeout(tick,100);return;}$('callout').textContent='GO!';setTimeout(()=>{if($('callout').textContent==='GO!')$('callout').textContent='';},500);if(role==='rider'&&!running)beginLocalRace();if(role==='host'&&room.status==='countdown')db.from('speedway_rooms').update({status:'racing',updated_at:new Date().toISOString()}).eq('id',room.id);if(role==='host')hostLoop();};tick();}
function beginLocalRace(){if(!bike)resetLocalBike();running=true;finishing=false;lastTs=performance.now();startTs=lastTs;lapStartTs=lastTs;$('controls').classList.remove('hidden');$('raceMsg').textContent='GO — auto throttle!';raf=requestAnimationFrame(loop);}
function updateProgress(nr,now){const N=trackPts.length,idx=nr.idx,last=bike.lastIdx,forward=(idx-last+N)%N,back=(last-idx+N)%N;if(nr.dist<126){if(forward>0&&forward<28){bike.progress_steps+=forward;bike.lastIdx=idx}else if(back<8){bike.lastIdx=idx}}const newLap=Math.floor(bike.progress_steps/N);if(newLap>bike.lap){bike.lap=newLap;const lt=now-lapStartTs;lapStartTs=now;lapTimes.push(lt);if(newLap<room.lap_count){$('callout').textContent='LAP '+(newLap+1);setTimeout(()=>{if(running)$('callout').textContent='';},500);$('raceMsg').textContent='Lap '+newLap+' · '+formatMs(lt);}else finishLocal(now);}}
function physics(dt,now){const steer=(leftHeld?-1:0)+(rightHeld?1:0);bike.steer+=(steer-bike.steer)*Math.min(1,dt*10);const nr=nearest(bike.x,bike.y),onShale=nr.dist<=TRACK_HALF,veryOff=nr.dist>128;let target=onShale?286:veryOff?103:158;if(Math.abs(bike.steer)>.75)target-=10;bike.speed+=(target-bike.speed)*Math.min(1,dt*(onShale?1.55:3.2));const steerRate=2.08*(.45+.55*Math.min(1,bike.speed/210));bike.heading+=bike.steer*steerRate*dt;const grip=onShale?1.72:2.5,vd=angleDiff(bike.vel_angle,bike.heading);bike.vel_angle+=vd*Math.min(1,grip*dt);bike.x+=Math.cos(bike.vel_angle)*bike.speed*dt;bike.y+=Math.sin(bike.vel_angle)*bike.speed*dt;if(!onShale&&!bike.off){bike.off=true;offTrackEvents++;}if(onShale&&bike.off)bike.off=false;if(veryOff){bike.farOffTime+=dt;if(bike.farOffTime>.45){bike.x+=(nr.p.x-bike.x)*Math.min(1,dt*2.6);bike.y+=(nr.p.y-bike.y)*Math.min(1,dt*2.6);bike.speed*=.985}}else bike.farOffTime=0;updateProgress(nr,now);}
async function pushState(force=false){if(!db||!room||!myId||!bike)return;const now=Date.now();if(!force&&now-lastPush<100)return;lastPush=now;const best=lapTimes.length?Math.round(Math.min(...lapTimes)):null;await db.from('speedway_riders').update({x:bike.x,y:bike.y,heading:bike.heading,vel_angle:bike.vel_angle,speed:bike.speed,steer:bike.steer,progress_steps:bike.progress_steps,lap:bike.lap,best_lap_ms:best,updated_at:new Date().toISOString()}).eq('id',myId);}
function loop(ts){if(!running)return;const dt=Math.min(.032,(ts-lastTs)/1000);lastTs=ts;physics(dt,ts);const elapsed=ts-startTs;$('timeHud').textContent=(elapsed/1000).toFixed(2);$('lapHud').textContent=Math.min(room.lap_count,bike.lap+1)+' / '+room.lap_count;$('bestHud').textContent=lapTimes.length?formatMs(Math.min(...lapTimes)):'—';const mine=riders.find(r=>r.id===myId);if(mine){mine.x=bike.x;mine.y=bike.y;mine.heading=bike.heading;mine.vel_angle=bike.vel_angle;mine.speed=bike.speed;mine.steer=bike.steer;mine.progress_steps=bike.progress_steps;mine.lap=bike.lap;mine.best_lap_ms=lapTimes.length?Math.round(Math.min(...lapTimes)):null;}renderRace();pushState(false);raf=requestAnimationFrame(loop);}
async function finishLocal(now){if(finishing||!running)return;finishing=true;running=false;cancelAnimationFrame(raf);const total=Math.round(now-startTs),best=Math.round(Math.min(...lapTimes));bike.finished=true;$('controls').classList.add('hidden');$('callout').textContent='🏁 FINISH!';$('raceMsg').textContent='Heat complete · '+formatMs(total);await db.from('speedway_riders').update({x:bike.x,y:bike.y,heading:bike.heading,vel_angle:bike.vel_angle,speed:bike.speed,steer:bike.steer,progress_steps:bike.progress_steps,lap:room.lap_count,finished:true,finish_ms:total,best_lap_ms:best,updated_at:new Date().toISOString()}).eq('id',myId);{const saved=await db.from('speedway_results').insert({room_id:room.id,rider_id:myId,race_number:room.race_number,player_name:(riders.find(r=>r.id===myId)||{}).name||'Rider',mode:'live',lap_count:room.lap_count,total_ms:total,best_lap_ms:best,lap_times_ms:lapTimes.map(Math.round),off_track_events:offTrackEvents,app_version:version()});if(saved.error&&saved.error.code!=='23505')console.error(saved.error);}await loadRiders();renderRace();}
let hostViewRunning=false;function hostLoop(){if(role!=='host'||!room||!['countdown','racing'].includes(room.status)||hostViewRunning)return;hostViewRunning=true;const tick=()=>{if(role!=='host'||!room||!['countdown','racing'].includes(room.status)){hostViewRunning=false;return;}const start=Date.parse(room.start_at||new Date().toISOString());$('timeHud').textContent=Math.max(0,(Date.now()-start)/1000).toFixed(2);renderRace();checkFinished();requestAnimationFrame(tick);};requestAnimationFrame(tick);}
async function checkFinished(){if(role!=='host'||!room||!riders.length)return;if(riders.length>=2&&riders.every(r=>r.finished)&&room.status!=='finished'){const {data}=await db.from('speedway_rooms').update({status:'finished',updated_at:new Date().toISOString()}).eq('id',room.id).select('*').single();if(data){room=data;renderResults();}}}
async function endRace(){if(role!=='host'||!room)return;const {data}=await db.from('speedway_rooms').update({status:'finished',updated_at:new Date().toISOString()}).eq('id',room.id).select('*').single();if(data){room=data;await loadRiders();renderResults();}}
async function closeRoom(){if(role==='host'&&room&&db)await db.from('speedway_rooms').update({status:'closed',updated_at:new Date().toISOString()}).eq('id',room.id);leaveLocal();}
async function leave(){if(role==='rider'&&myId&&db){try{await db.from('speedway_riders').delete().eq('id',myId);}catch(_){}}leaveLocal();}
async function leaveLocal(){running=false;cancelAnimationFrame(raf);if(channel&&db)try{await db.removeChannel(channel);}catch(_){}channel=null;room=null;riders=[];role=null;myId=null;bike=null;show('choice');}

function press(which,on){if(which==='left'){leftHeld=on;$('leftBtn').classList.toggle('active',on)}else{rightHeld=on;$('rightBtn').classList.toggle('active',on)}}
function bind(btn,which){const down=e=>{if(e.cancelable)e.preventDefault();press(which,true);},up=e=>{if(e.cancelable)e.preventDefault();press(which,false);};btn.addEventListener('pointerdown',down,{passive:false});btn.addEventListener('pointerup',up,{passive:false});btn.addEventListener('pointercancel',up,{passive:false});btn.addEventListener('touchstart',down,{passive:false});btn.addEventListener('touchend',up,{passive:false});btn.addEventListener('touchcancel',up,{passive:false});btn.addEventListener('contextmenu',e=>e.preventDefault());}
bind($('leftBtn'),'left');bind($('rightBtn'),'right');
window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();press('left',true)}if(e.key==='ArrowRight'){e.preventDefault();press('right',true)}});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft')press('left',false);if(e.key==='ArrowRight')press('right',false)});

$('chooseHost').onclick=()=>show('hostSetup');$('chooseJoin').onclick=()=>show('joinSetup');document.querySelectorAll('.backChoice').forEach(b=>b.onclick=()=>show('choice'));
$('joinCode').addEventListener('input',e=>e.target.value=cleanCode(e.target.value));$('createRoom').onclick=createRoom;$('joinRoom').onclick=joinRoom;$('startRace').onclick=startRace;$('endRace').onclick=endRace;$('raceAgain').onclick=resetRoomForHeat;$('resultRaceAgain').onclick=resetRoomForHeat;$('closeRoom').onclick=closeRoom;$('resultClose').onclick=closeRoom;$('leaveRoom').onclick=leave;$('resultLeave').onclick=leave;
document.addEventListener('visibilitychange',()=>{if(document.hidden){press('left',false);press('right',false);}});

renderTrack();loadAllTimeBoard();
if(!configured)setService('Supabase not configured',false);else setService('Online service ready',true);
const params=new URLSearchParams(location.search),join=params.get('join'),mode=params.get('mode'),prefillName=params.get('name');if(prefillName)$('riderName').value=cleanName(prefillName);if(join){$('joinCode').value=cleanCode(join);show('joinSetup');}else if(mode==='host')show('hostSetup');else if(mode==='join')show('joinSetup');
})();
